entryJsonInHtmlKm(
    [
        {
            "surname": "CHHORN",
            "givenName": "Chhayyuth",
            "middleName": "",
            "is_ready": "yes",
            "name_en": "CHHORN Chhayyuth",
            "name_km": "ឆន ឆៃយុទ្ធ",
            "position_en": "M&E/EdTech Coordinator",
            "position_km": "ប្រធានផ្នែកបច្ចេកវិទ្យាសម្រាប់ការអប់រំ",
            "organization_en": "Kampuchea Action to Promote Education",
            "organization_km": "អង្គការសកម្មភាពដើម្បីការអប់រំនៅកម្ពុជា",
            "imgUrl": "https://drive.google.com/file/d/1Z_T9ZeJyWWF_R_vbT3TOkfpPZh1kYxla/view?usp=sharing",
            "imgAlt": "chhorn-chhayyuth",
            "projectUrl": "-",
            "modalId": "chhorn-chhayyuth",
            "bio_en": "Working as M&E Coordinator, Data is really important to tracking the progress of activities and progress of indicator achievements of project as well as organization goals. Data Visualization which enable the audience to see data explanation or the storytelling of data easily. Develop the data visualization dashboard for KAPE organization.",
            "bio_km": "ក្នុងនាម​ជា​អ្នកសម្របសម្រួល​ផ្នែក​តាមដាន ​និង​វាយតម្លៃ ទិន្នន័យ​ពិតជា​មាន​សារៈសំខាន់​ណាស់​ក្នុង​ការ​តាមដាន​វឌ្ឍនភាព​នៃ​សកម្មភាព និង​សូចនាករ​សមិទ្ធិ​ផល​នៃ​គម្រោង ក៏ដូចជា​គោលដៅ​របស់​អង្គការ។ ការ​ធ្វើ​ទិន្នន័យ​ឱ្យ​ក្លាយជា​រូបភាព​អាច​ឱ្យ​ទស្សនិកជន​មើលឃើញ​ការ​ពន្យល់​អំពី​ទិន្នន័យ ​ឬការ​និទានរឿង​នៃ​ទិន្នន័យ​បាន​យ៉ាង​ងាយស្រួល។",
            "wpImgUrl": "https://opendevelopmentcambodia.net/wp-content/uploads/sites/2/2020/04/chhorn-chhayyuth-min.jpg"
        },
        {
            "surname": "CHHORN",
            "givenName": "Reakshar",
            "middleName": "",
            "is_ready": "yes",
            "name_en": "CHHORN Reakshar",
            "name_km": "ឈន រក្សា",
            "position_en": "Siem Reap Office Coordinator",
            "position_km": "អ្នកសម្របសម្រួលប្រចាំការិយាល័យសៀមរាប",
            "organization_en": "Transparency International Cambodia",
            "organization_km": "តម្លាភាពកម្ពុជា",
            "imgUrl": "https://drive.google.com/file/d/1fsif15Mn7VFOxrWfLnCkTAS6g5FEWlno/view?usp=sharing",
            "imgAlt": "chhorn-reakshar",
            "projectUrl": "-",
            "modalId": "chhorn-reakshar",
            "bio_en": "Data is very important for me because I want to use it as a tool to understand and follow up on the changing of the world and my country. For example, following the inflation rate of a country in one period and comparing it to other countries. In addition to this, I intend to utilize data by finding useful and up-to-date data and then use it in any decisions making like a strategic plan for my current workplace and show it to other people to know about the data-related issues. From literacy data training, I expect to learn the useful tools for using in data searching and making it usable data. Moreover, I want to know about international and national websites for searching for data. After the training, I want to make a research paper related to youth engagement in decision making at the grassroots level by using any tools and knowledge from this training.",
            "bio_km": "ទិន្នន័យ​មាន​សារៈសំខាន់​ណាស់​សម្រាប់​ខ្ញុំ ព្រោះ​ខ្ញុំ​ចង់​ប្រើ​វា​ជា​ឧបករណ៍​ដើម្បី​ស្វែងយល់​ និង​តាមដាន​ការ​ផ្លាស់​ប្តូរ​របស់​ពិភពលោក និង​ប្រទេស​របស់ខ្ញុំ។ ឧទាហរណ៍ ការ​តាមដាន​ពីអ​ត្រា​អតិផរណា​នៃ​ប្រទេស​មួយ​ក្នុងរយៈពេល​មួយ ហើយ​ប្រៀបធៀប​វា​ទៅ​ប្រទេស​ដទៃទៀត។ បន្ថែម​ពីលើ​នេះ ខ្ញុំ​មានបំណង​ប្រើប្រាស់​ទិន្នន័យ ដោយ​ស្វែងរក​ទិន្នន័យ​ដែល​មានប្រយោជន៍​ និង​មាន​បច្ចុប្បន្នភាព មក​ប្រើ​វា​ក្នុង​ការសម្រេច​ចិត្ត​ណាមួយ​ដូចជា ផែនការ​យុទ្ធសាស្ត្រ​សម្រាប់​កន្លែង​ធ្វើការ​បច្ចុប្បន្ន​របស់ខ្ញុំ ហើយ​បង្ហាញ​វា​ដល់​មនុស្ស​ផ្សេងទៀត​ឱ្យ​ដឹង​អំពី​ព័ត៌មាន​ដែល​ទាក់ទង​នឹង​ទិន្នន័យ។ ខ្ញុំ​រំពឹង​ថា​ នឹង​រៀន​ឧបករណ៍​មានប្រយោជន៍​សម្រាប់​ប្រើ​ក្នុង​ការស្វែងរក​ទិន្នន័យ​ និង​ធ្វើ​ឱ្យ​ទិន្នន័យ​អាច​ប្រើ​បាន។ លើស​ពីនេះ​ទៅទៀត​ ខ្ញុំ​ចង់​ដឹង​អំពី​គេហទំព័រ​ជាតិ​ និង​អន្តរជាតិ​សម្រាប់​ស្វែងរក​ទិន្នន័យ។ បន្ទាប់ពី​ការ​បណ្តុះបណ្តាល​ ខ្ញុំ​ចង់​បង្កើតឯកសារ​ស្រាវជ្រាវ​ទាក់ទង​នឹង​ការចូលរួម​របស់​យុវជន​ក្នុង​ការសម្រេច​ចិត្ត​នៅ​ថ្នាក់​មូលដ្ឋាន​ដោយ​ប្រើ​ឧបករណ៍ ​និង​ចំណេះដឹង​ណាមួយ​ពី​ការ​បណ្តុះបណ្តាល​នេះ។",
            "wpImgUrl": "https://opendevelopmentcambodia.net/wp-content/uploads/sites/2/2020/04/chhorn-reakshar-min.jpg"
        },
        {
            "surname": "CHORN",
            "givenName": "Chanbota",
            "middleName": "",
            "is_ready": "no",
            "name_en": "CHORN Chanbota",
            "name_km": "",
            "position_en": "",
            "position_km": "",
            "organization_en": "",
            "organization_km": "",
            "imgUrl": "",
            "imgAlt": "chorn-chanbota",
            "projectUrl": "-",
            "modalId": "chorn-chanbota",
            "bio_en": "",
            "bio_km": "",
            "wpImgUrl": ""
        },
        {
            "surname": "DY",
            "givenName": "Vutheara",
            "middleName": "",
            "is_ready": "yes",
            "name_en": "DY Vutheara",
            "name_km": "ឌី  វុទ្ធារ៉ា",
            "position_en": "Communication Officer",
            "position_km": "មន្រ្តីទំនាក់ទំនង",
            "organization_en": "RECOFTC",
            "organization_km": "រីខូហ្វ",
            "imgUrl": "https://drive.google.com/file/d/1OtWr_BFwts1v4wyM_DD_t3hJFue5zcMg/view?usp=sharing",
            "imgAlt": "dy-vutheara",
            "projectUrl": "-",
            "modalId": "dy-vutheara",
            "bio_en": "Data is important because it helps me to produce more attractive and reliable document for audience to see, so they are able to better understand the situation not only in Cambodia but also what happens in other regions and around the globe. I expect to learn where I can get data, how to use it in the way that can draw attention my audience to interest more in the issue that I try to share them. I would like to share this piece of document to my colleague and donor through the project that RECOFTC is working on called V4MF that focusing on forest governance, and to public person to be aware of what has been happening between women and forest governance and effort we have been trying to support the gender equality in forest management process and way forward.",
            "bio_km": "ទិន្នន័យមានសារសំខាន់ព្រោះវាជួយឱ្យខ្ញុំបង្កើតឯកសារគួរឱ្យទាក់ទាញ និងគួរឱ្យទុកចិត្តសម្រាប់ទស្សនិកជនដើម្បីពួកគេអាចយល់ច្បាស់ពីស្ថានភាពមិនត្រឹមតែនៅក្នុងប្រទេសកម្ពុជាទេ នៅជុំវិញពិភពលោកផងដែរ។ ខ្ញុំរំពឹងថាអាចចេះវិធីរកទិន្នន័យ និងវិធីដែលអាចទាក់ទាញចំណាប់អារម្មណ៍ទស្សនិកជនរបស់ខ្ញុំទៅលើបញ្ហាដែលខ្ញុំព្យាយាមចែកចាយទៅពួកគេ។ ខ្ញុំចង់ចែករំលែកឯកសារនេះទៅមិត្តរួមការងារ និងម្ចាស់ជំនួយរបស់ខ្ញុំតាមរយៈគំរោងដែល រីខូហ្វ កំពុងធ្វើដែលហៅថា V4MF ដែលផ្តោតលើអភិបាលកិច្ចព្រៃឈើ និងដើម្បីឱ្យសាធារណជនយល់ដឹងអំពីអ្វីដែលកំពុងកើតឡើងរវាងស្ត្រីនិងអភិបាលកិច្ចព្រៃឈើ ក៏ដូចជាការខិតខំរបស់យើងក្នុងសមភាពយេនឌ័រក្នុងដំណើរការគ្រប់គ្រងព្រៃឈើ។",
            "wpImgUrl": "https://opendevelopmentcambodia.net/wp-content/uploads/sites/2/2020/05/dy-vutheara-min.jpg"
        },
        {
            "surname": "HANG",
            "givenName": "Hybunna",
            "middleName": "",
            "is_ready": "yes",
            "name_en": "HANG Hybunna",
            "name_km": "ហង់ ហ៊ីប៊ុណ្ណា",
            "position_en": "Water, Sanitation and Hygiene Specialist",
            "position_km": "អ្នកឯកទេសទឹកស្អាត និងអនាម័យ",
            "organization_en": "Plan International Cambodia",
            "organization_km": "អង្គការភ្លែនអន្តរជាតិកម្ពុជា",
            "imgUrl": "https://drive.google.com/file/d/1I4Du7nvyP29dM8rPn2KSRyxI1V24zxs0/view?usp=sharing",
            "imgAlt": "hang-hybunna",
            "projectUrl": "-",
            "modalId": "hang-hybunna",
            "bio_en": "I could say that Data is a King which is very important for my daily work since I do need to utilize it for presenting data/information with visualization in order to effectively engage with the public for reaching a wider audience. Upon completion of the training, I will learn more of the concept of open data strengthen my organization’s position, as well as my responsible programmes in using data effectively.",
            "bio_km": "ខ្ញុំ​អាច​និយាយ​បាន​ថា ​ទិន្នន័យ​គឺជា​ស្តេច​ដែល​មាន​សារៈសំខាន់​ខ្លាំង​ណាស់​សម្រាប់​ការងារ​ប្រចាំថ្ងៃ​របស់ខ្ញុំ ព្រោះ​ខ្ញុំ​ត្រូវការ​ប្រើ​វា​សម្រាប់​បង្ហាញ​ទិន្នន័យ ឬព័ត៌មាន​ដែល​អាច​មើលឃើញ ដើម្បី​អាច​ចូលរួម​ឱ្យ​កាន់តែមាន​ប្រសិទ្ធិ​ភាព​ក្នុង​ការចែកចាយ​ទៅដល់​ទស្សនិកជន​ទូទៅ។ ខ្ញុំ​នឹង​រៀន​បន្ថែម​ទៀត​នូវទស្សនាទាន​នៃ​ទិន្នន័យ​បើកទូលាយ ពង្រឹង​ជំហរ​របស់​អង្គភាព ក៏ដូចជា​កម្មវិធី​ដែល​ស្ថិត​ក្រោម​ការទទួលខុសត្រូវ​របស់ខ្ញុំ ក្នុង​ការប្រើ​ប្រាស់​ទិន្នន័យ​ប្រកបដោយ​ប្រសិទ្ធភាព។",
            "wpImgUrl": "https://opendevelopmentcambodia.net/wp-content/uploads/sites/2/2020/04/hang-hybunna-min.jpg"
        },
        {
            "surname": "HIEV",
            "givenName": "Hokkheang",
            "middleName": "",
            "is_ready": "yes",
            "name_en": "HIEV Hokkheang",
            "name_km": "ហៀវ ហុកឃាង",
            "position_en": "Research Assistant",
            "position_km": "ជំនួយការស្រាវជ្រាវ",
            "organization_en": "Cambodia Development Resource Institute",
            "organization_km": "វិទ្យាស្ថាន​បណ្តុះបណ្តាល និង​ស្រាវជ្រាវ​ដើម្បី​អភិវឌ្ឍន៍​កម្ពុជា​",
            "imgUrl": "https://drive.google.com/file/d/1yjqY0zHwT-g4cNRthvMHypLlxgJLzSet/view?usp=sharing",
            "imgAlt": "hiev-hokkheang",
            "projectUrl": "-",
            "modalId": "hiev-hokkheang",
            "bio_en": "Without data, we cannot know for sure if our assumption or hypothesis is right or wrong. With it, we can analyse, make a conclusion and give appropriate reponse to various issues. I expect to further understand nature of data, learn different ways to gather data and know more open data sources. I want to be able to convey analysis of data/results correctly and interestingly in a manner readers can easily understand and see another side of various issues. Using data sets from Cambodia Socio-Economic Surveys, I plan to elaborate more on unpaid family workers in Cambodia especially its trend in agricultural and service sector and their socio-economic characteristics.",
            "bio_km": "បើសិនជា​គ្មាន​ទិន្នន័យទេ យើង​មិន​អាច​ដឹង​ច្បាស់​ថា​ ការ​សន្និដ្ឋាន​របស់​យើង​ត្រូវ​ ឬខុស​ឡើយ។ ជាមួយ​ទិន្នន័យ យើង​អាច​វិភាគ ធ្វើ​សេចក្តី​សន្និដ្ឋាន និង​ផ្តល់​នូវ​ការ​ឆ្លើយតប​មួយ​ដ៏​សមរម្យ​ទៅកាន់​បញ្ហា​នានា។ ខ្ញុំ​រំពឹង​ថា ខ្ញុំ​នឹងអាច​យល់​ពី​ធម្មជាតិ​នៃ​ទិន្នន័យ រៀន​ពី​វិ​ធី​សាស្ត្រផ្សេង​ៗក្នុង​ការ​ប្រមូល​ទិន្នន័យ និង​ដឹងពី​ប្រភព​ទិន្នន័យ​បើក​ទូ​លាយ​ផ្សេង​ៗទៀត។ ខ្ញុំ​ចង់​ចេះ​បង្ហាញ​ទិន្នន័យ​ ឬលទ្ធផល​អ្វីមួយ​ឱ្យ​បាន​ត្រឹមត្រូវ និង​មាន​ភាព​ទាក់ទាញ ​ដើម្បី​ឱ្យ​អ្នកអាន​ងាយ​យល់ និង​អាច​ឃើញ​ពី​ផ្នែក​មួយទៀត​នៃ​បញ្ហា​អ្វីមួយ។ តាមរយៈការប្រើ​ប្រាស់​ទិន្នន័យ​បានមក​ពីការ​អង្កេត​សេដ្ឋកិច្ច​សង្គម​របស់​ប្រទេស​កម្ពុជា​ ខ្ញុំ​គ្រោង​នឹង​បង្ហាញ​ពី សមាជិកគ្រួសារ​ដែល​មិនបាន​ទទួល​ប្រាក់​កម្រៃ​នៅក្នុង​ប្រទេស​កម្ពុជា ជាពិសេស​និន្នាការ​នៅក្នុង​វិស័យ​កសិកម្ម និង​សេវាកម្ម​ និង​លក្ខណៈ​សេដ្ឋកិច្ច​សង្គម​របស់​ពួក​គាត់។",
            "wpImgUrl": "https://opendevelopmentcambodia.net/wp-content/uploads/sites/2/2020/04/hiev-hokkheang-min.jpg"
        },
        {
            "surname": "Hor",
            "givenName": "Otdam",
            "middleName": "",
            "is_ready": "no",
            "name_en": "Hor Otdam",
            "name_km": "",
            "position_en": "",
            "position_km": "",
            "organization_en": "",
            "organization_km": "",
            "imgUrl": "",
            "imgAlt": "hor-otdam",
            "projectUrl": "-",
            "modalId": "hor-otdam",
            "bio_en": "",
            "bio_km": "",
            "wpImgUrl": ""
        },
        {
            "surname": "KHORN",
            "givenName": "Champa",
            "middleName": "",
            "is_ready": "yes",
            "name_en": "KHORN Champa",
            "name_km": "ខន ចំប៉ា",
            "position_en": "Deputy Editor-in-chief",
            "position_km": "និពន្ធនាយករង",
            "organization_en": "Thmey Thmey News",
            "organization_km": "ថ្មីៗ",
            "imgUrl": "https://drive.google.com/file/d/1dTnbjOrn_LgooZbpIh3W6PoERYaZQlDw/view?usp=sharing",
            "imgAlt": "khorn-champa",
            "projectUrl": "-",
            "modalId": "khorn-champa",
            "bio_en": "I have been working as a journalist for 7 years. Data is very important for me as a journalist. I can write a piece which is contain more data and make it into difference format such as infographic, map and our reader can easily understand the piece. I hope that I could gain more knowledge related to data in this training and I will share to my colleagues.",
            "bio_km": "ខ្ញុំ​ធ្វើជា​អ្នកសារព័ត៌អស់​រយៈពេល ៧ឆ្នាំ​ហើយ។ ទិន្នន័យ​ពិតជា​មាន​សារៈសំខាន់​ណាស់​សម្រាប់​ខ្ញុំ​ដែល​ជា​អ្នកសារព័ត៌មាន​ម្នាក់។ ខ្ញុំ​អាច​សរសេរ​អត្ថបទ​ដែល​មាន​ទិន្នន័យ ហើយ​បម្លែង​វា​ទៅជា​ទម្រង់​ផ្សេង​ៗដូចជា infographic ឬ ផែនទី ដែល​អាច​ឱ្យ​អ្នកអាន​ងាយ​យល់។ ខ្ញុំ​សង្ឃឹមថា ​ខ្ញុំ​អាច​ទទួល​បាន​ចំណេះដឹង​ទាក់ទង​ទិន្នន័យ ពី​វគ្គ​បណ្តុះបណ្តាល​នេះ ហើយ​ខ្ញុំ​នឹង​ចែករំលែក​ចំណេះដឹង​នេះ​ទៅ​មិត្ត​រួមការ​ងារ​ផង​ដែរ។",
            "wpImgUrl": "https://opendevelopmentcambodia.net/wp-content/uploads/sites/2/2020/04/khorn-champa-min.jpg"
        },
        {
            "surname": "Khuon",
            "givenName": "Sovanvatey",
            "middleName": "",
            "is_ready": "yes",
            "name_en": "Khuon Sovanvatey",
            "name_km": "ឃួន​​ សុវណ្ណវត្តី",
            "position_en": "National Volunteer",
            "position_km": "អ្នកស្ម័គ្រចិត្តក្នុងស្រុក",
            "organization_en": "VSO Cambodia",
            "organization_km": "អង្គការ​អ្នក​ស្ម័គ្រចិត្ត​បំរើ​ការងារ​នៅ​បរទេស​",
            "imgUrl": "https://photos.google.com/share/AF1QipOJakNbPbfN8VFgXpDqv-zZUPHlfxEKMM3fkP0mj0L7QtkY_pgQ-T36D_aQlp7ULg?key=MjBQS2JJcU5vUGZqSm1veHdNT0xVRkxEcDB3ZlJn",
            "imgAlt": "khuon-sovanvatey",
            "projectUrl": "-",
            "modalId": "khuon-sovanvatey",
            "bio_en": "As a digital storyteller, I am referring data to highlight the impact of youth and volunteering to inspired Cambodia youth to get involved in volunteering and empower employability. Data Literacy training equipped with the skills and tools necessary for a data-based researcher like me to publish the powerful story to make change in the community.",
            "bio_km": "ក្នុងនាម​ជា​អ្នកនិទាន​រឿង​បែប​ឌីជីថល ខ្ញុំ​ប្រើប្រាស់​ទិន្នន័យ​ដើម្បី​បង្ហាញ​ពី​ផល​ប៉ះពាល់ជា​វិជ្ជមាន​នៃ​យុវជន ​និង​ការ​ស្ម័គ្រចិត្ត ដើម្បី​លើកទឹកចិត្ត​ឱ្យ​យុជ​នក​ម្ពុ​ជា​ចូលរួម​ក្នុង​ការងារ​ស្ម័គ្រចិត្ត​ និង​ផ្តល់​អំណាច​ដល់​ភាព​មានការ​ងារ​ធ្វើ។ ការ​បណ្តុះបណ្តាល​ចំណេះដឹង​ផ្នែក​អក្ខរកម្ម​ទិន្នន័យ​ផ្តល់នូវ​ជំនាញ​ និង​ឧបករណ៍​ចាំបាច់​សម្រាប់​អ្នកស្រាវជ្រាវ​ដែល​មាន​មូលដ្ឋាន​លើ​ទិន្នន័យ​ដូចជា​ខ្ញុំ​ ដើម្បី​បោះពុម្ព​ផ្សាយ​រឿងរ៉ាវ​ដ៏​មាន​ឥទ្ធិពល​ដើម្បី​ធ្វើការ​ផ្លាស់​ប្តូរ​នៅក្នុង​សហគមន៍។",
            "wpImgUrl": "https://opendevelopmentcambodia.net/wp-content/uploads/sites/2/2020/04/khuon-sovanvatey-min.jpg"
        },
        {
            "surname": "KOL",
            "givenName": "Leakhana",
            "middleName": "",
            "is_ready": "yes",
            "name_en": "KOL Leakhana",
            "name_km": "កុល លក្ខណា",
            "position_en": "Independent Consultant",
            "position_km": "ទីប្រឹក្សាឯករាជ្យ",
            "organization_en": "Self-employed",
            "organization_km": "ទីប្រឹក្សាឯករាជ្យ",
            "imgUrl": "https://drive.google.com/file/d/1a38uL66bxQO8Vs8tvjIJ2IHTLRbrDgCD/view?usp=sharing",
            "imgAlt": "kol-leakhana",
            "projectUrl": "-",
            "modalId": "kol-leakhana",
            "bio_en": "In general, data is for information which most of news, reports come to data refers to information that easy to access and it is a good proof for research report and others. I want to know more about function and programs which related to data and using it for working. After the training, I will complete my story telling project.",
            "bio_km": "ជាទូទៅ ទិន្នន័យ​ត្រូវ​បាន​ប្រើប្រាស់​ជា​ព័ត៌មាន​នៅក្នុងអត្ថបទ​សារព័ត៌មាន របាយការណ៍ ហើយ​វា​ជួយ​ផ្តល់​ជា​អំណះអំណាង​បន្ថែម​ទៅលើ​អត្ថបទ ក៏ដូចជា​កិច្ចការ​ស្រាវជ្រាវ​ទាំងនោះ។ ខ្ញុំ​ចង់​រៀន​បន្ថែម​ពីមុខ​ងារ និង​កម្មវិធី​ប្រើប្រាស់​ទាក់ទង​នឹង​ទិន្នន័យ។ ដូច្នេះ ចុងបញ្ចប់​នៃ​គម្រោង ខ្ញុំ​ចង់​ធ្វើ​របាយការណ៍​ដែល​មាន​រួមបញ្ចូល​ការ​បង្ហាញ​ទិន្នន័យ។",
            "wpImgUrl": "https://opendevelopmentcambodia.net/wp-content/uploads/sites/2/2020/04/kol-leakhana-min.jpg"
        },
        {
            "surname": "LY",
            "givenName": "Vichheka",
            "middleName": "",
            "is_ready": "yes",
            "name_en": "LY Vichheka",
            "name_km": "លី​​ វិច្ឆិកា",
            "position_en": "Research Assistant",
            "position_km": "ជំនួយការស្រាវជ្រាវ",
            "organization_en": "Planete Enfants & Developpement",
            "organization_km": "អង្គការពិភពកុមារ និងអភិវឌ្ឍន៍",
            "imgUrl": "https://drive.google.com/file/d/1Qd5Uh9DanBTSd3LkGcfk1mv7CSDx3Iqq/view?usp=sharing",
            "imgAlt": "ly-vichheka",
            "projectUrl": "-",
            "modalId": "ly-vichheka",
            "bio_en": "In research field, data is very important for me because data demonstrates and proves our findings. Personally, my expectation from this training is that I want to improve more of data analysis skills and research writing. After the training, what I want to achieve is to produce a good writing research and good at data entry.",
            "bio_km": "សម្រាប់​អ្នកធ្វើការ​ងារ​ស្រាវជ្រាវ​ដូច​ខ្ញុំ ទិន្នន័យ​ពិតជា​មាន​សារៈសំខាន់​ណាស់ ព្រោះ​វា​ជួយ​ពន្យល់ និង​ផ្តល់​ភស្តុតាង​ទៅ​ឱ្យ​ការ​រក​ឃើញ​របស់​ពួក​យើង។ ខ្ញុំ​រំពឹង​ថា​នឹងអាច​ពង្រឹង​ជំនាញ​វិភាគ​ទិន្នន័យ និង​ការស្រាវជ្រាវ។ បន្ទាប់ពី​វគ្គ​បណ្តុះបណ្តាល​នេះ ខ្ញុំ​ចង់​សរសេរ​កិច្ចការ​ស្រាវជ្រាវ និង​បញ្ចូល​ទិន្នន័យ​ឱ្យ​កាន់តែ​ប្រសើរឡើង។",
            "wpImgUrl": "https://opendevelopmentcambodia.net/wp-content/uploads/sites/2/2020/04/ly-vichheka-min.jpg"
        },
        {
            "surname": "MAO",
            "givenName": "Samnang",
            "middleName": "",
            "is_ready": "yes",
            "name_en": "MAO Samnang",
            "name_km": "ម៉ៅ សំណាង",
            "position_en": "Journalist",
            "position_km": "អ្នកសារព័ត៌មាន",
            "organization_en": "PNN TV",
            "organization_km": "ស្ថានីយ៍ទូរទស្សន៍ ភីអិនអិន",
            "imgUrl": "https://drive.google.com/file/d/1yGf2upOl7kiIVvs8vRdqTUJXyXSATMmj/view?usp=sharing",
            "imgAlt": "mao-samnang",
            "projectUrl": "-",
            "modalId": "mao-samnang",
            "bio_en": "Data is a very new concept to me espeically when using it in news stories to. It does not mean I have never used data in my stories, but the data that I have had seems to not yet be enough and complete. To me, data is a very important information source in news stories; if a story does not have clear data, it does not show every angle of the story in an accurate manner to the public. Data is a crucial evidence that can measure the level and scale of a story. As a journalist, we do not just quote someone's opinion, but we also have to verify the information that we got the. In short, data-driven story provides evidence to the readers and acts a document for research and study purposes.",
            "bio_km": "កាលណានិយាយដល់ទិន្នន័យក្នុងព័ត៌មាន វាហាក់ដូចជារឿងថ្មីមួយសម្រាប់ខ្ញុំក្នុងការផលិតព័ត៌មានដែលមានទិន្នន័យជាក់លាក់និងច្បាស់លាស់។ មិនមែនមានន័យថា ខ្ញុំពុំធ្លាប់ប្រើប្រាស់ទិន្នន័យសម្រាប់ព័ត៌មាន ឬដាក់នៅក្នុងព័ត៌មាននោះទេ ប៉ុន្តែតទិន្នន័យដែលខ្ញុំប្រើកន្លងមកមិនទាន់ទូលំទូលាយនិងទាញយកពីគ្រប់ប្រភពឡើយ។ សម្រាប់ខ្ញុំ ទិន្នន័យគឺជាប្រភពព័ត៌មានដ៏សំខាន់នៅក្នុងព័ត៌មាន។ ប្រសិនបើព័ត៌មានមានមួយ មិនមានទិន្នន័យច្បាស់លាស់និងជាក់លាក់នោះទេ នោះមានន័យថាព័ត៌មានទាំងនោះមិនបានបង្ហាញពីគ្រប់ជ្រុងជ្រោយ ឬត្រឹមត្រូវដល់សាធារណជនឡើយ។ ទិន្នន័យគឺជាភស្តុតាងដ៏សំខាន់ដែលអាចវាស់វែងពីកម្រិតនិងទំហំព័ត៌មានមួយឲ្យកាន់តែច្បាស់បន្ថែមទៀត។ ក្នុងនាមជាអ្នកសារព័ត៌មានយើងមិនអាចរាយការណ៍ឬគ្រាន់តែដកស្រង់សម្រង់សម្ដីរបស់ប្រភពមកចុះផ្សាយនោះទេ ការងាររបស់យើងមួយទៀត គឺការផ្ទៀងផ្ទាត់ព័ត៌មាន ការផ្ទៀងផ្ទាត់ទិន្នន័យព័ត៌មាន និងការបង្កើតទិន្នន័យនៅក្នុងព័ត៌មានដែលប្រមូលបានពីគ្រប់ប្រភពផ្សេងៗ។ ជារួមមក ការផលិតព័ត៌មានដោយមានដាក់បញ្ចូលនូវទិន្នន័យ ជាការបង្ហាញបន្ថែមនូវប្រភពច្បាស់លាស់នៃព័ត៌មានទៅដល់សាធារណជន ព្រមទាំងក្លាយទៅជាឯកសារមួយយ៉ាងសំខាន់សម្រាប់ការសិក្សាស្រាវជ្រាវឬការវាយតម្លៃអ្វីមួយដែលសាធារណជនចង់បានបាន។",
            "wpImgUrl": "https://opendevelopmentcambodia.net/wp-content/uploads/sites/2/2020/04/mao-samnang-min.jpg"
        },
        {
            "surname": "MEN",
            "givenName": "Vannavy",
            "middleName": "",
            "is_ready": "no",
            "name_en": "MEN Vannavy",
            "name_km": "ម៉ែន វណ្ណាវី",
            "position_en": "Freelance Consultant",
            "position_km": "ទីប្រឹក្សាឯករាជ្យ",
            "organization_en": "Self-employed",
            "organization_km": "ទីប្រឹក្សាឯករាជ្យ",
            "imgUrl": "",
            "imgAlt": "men-vannavy",
            "projectUrl": "-",
            "modalId": "men-vannavy",
            "bio_en": "",
            "bio_km": "",
            "wpImgUrl": ""
        },
        {
            "surname": "MITH",
            "givenName": "Samonn",
            "middleName": "",
            "is_ready": "yes",
            "name_en": "MITH Samonn",
            "name_km": "មិត្ត សាម៉ុន",
            "position_en": "Monitoring and Evaluation Coordinator",
            "position_km": "អ្នកតាមដាន និងការវាយតម្លៃ",
            "organization_en": "WorldFish",
            "organization_km": "វើលហ្វ៊ីស",
            "imgUrl": "",
            "imgAlt": "mith-samonn",
            "projectUrl": "-",
            "modalId": "mith-samonn",
            "bio_en": "I understand that data forms an important part for handling his daily tasks, especially for situation analysis, decision making and planning. Though, I have firsthand experience in working with data, I feel there is a room for improving my skills in exploiting and interacting with different datasets more efficiently. Attending the Data Literacy Training, I aim at strengthen my skills in data mining and putting dataset together to find out most interesting story potentially hidden inside the data. Besides this, I am looking for opportunity for expanding my professional network for data sharing and for accessing to different datasets from different data sources. After the training, I expect to be more efficient in collecting and using secondary data from different sources for telling a story for the purpose of social development.",
            "bio_km": "ខ្ញុំ​យល់ថា​ ទិន្នន័យ​ជាផ្នែក​មួយ​ដ៏​សំខាន់​ក្នុង​ការអនុវត្ត​ការងារ​ប្រចាំថ្ងៃ​របស់ខ្ញុំ ជាពិសេស​សម្រាប់​ការវិភាគ​ស្ថានភាព ការសម្រេច​ចិត្ត និង​ការ​ធ្វើ​ផែនការ។ បើទោះបីជា​ខ្ញុំ​មានបទពិសោធន៍​ផ្ទាល់​ជាមួយ​ទិន្នន័យ ខ្ញុំ​មាន​អារម្មណ៍​ថា ខ្ញុំ​នៅ​មាន​ចំណុច​ត្រូវ​ពង្រឹង​ទាក់ទង​នឹង​ជំនាញ​ក្នុង​ការប្រើ​ប្រាស់​ទិន្នន័យ​ឱ្យ​កាន់តែ​មានប្រសិទ្ធភាព។ ក្នុង​ការចូលរួម​វគ្គ​បណ្តុះបណ្តាល​នេះ ខ្ញុំ​សង្ឃឹមថា ខ្ញុំ​អាច​ពង្រឹង​ជំនាញ​របស់ខ្ញុំ​ក្នុង​ការ​ទាញ​យក​ទិន្នន័យ និង​ដាក់​វា​បញ្ចូល​គ្នា ​ដើម្បី​អាច​ស្វែងរក​ព័ត៌មាន​ដែល​មាន​ភាព​ទាក់ទាញ ដែល​អាច​បង្កប់​នៅ​ក្នុង​ទិន្នន័យ​នោះ។ ក្រៅពី​នេះ​ដែរ ខ្ញុំ​ក៏​ចង់​សែ្វ​ងរ​កឱកាស​ពង្រីក​បណ្តាញ​ការងារ​សម្រាប់​ការចែក​រំលែក​ទិន្នន័យ និង​ការ​ចូល​ទៅ​ប្រើប្រាស់​ទិន្នន័យ​ពី​ប្រភព​ផ្សេង​ៗ។ បន្ទាប់ពី​វគ្គ​បណ្តុះបណ្តាល​នេះ ខ្ញុំ​រំពឹង​ថា ​នឹងអាចប្រមូល ​និង​ប្រើប្រាស់​ទិន្នន័យ​ពី​ប្រភព​ផ្សេង​ៗគ្នា​សម្រាប់​គោលបំណង​នៃ​ការ​អភិវឌ្ឍ​សង្គម​កាន់តែ​មានប្រសិទ្ធភាព។",
            "wpImgUrl": "https://opendevelopmentcambodia.net/wp-content/uploads/sites/2/2017/11/Icon-User-green.png"
        },
        {
            "surname": "NARA",
            "givenName": "Nou",
            "middleName": "Alyny",
            "is_ready": "yes",
            "name_en": "NARA Nou Alyny",
            "name_km": "ណារ៉ា នូ អាលីនី",
            "position_en": "Senior Program Support Officer",
            "position_km": "មន្ត្រីកម្មវិធីជាន់ខ្ពស់",
            "organization_en": "Srer Khmer",
            "organization_km": "ស្រែខ្មែរ",
            "imgUrl": "https://drive.google.com/file/d/1Ngq0z17WTDxjsP4muWz_YrE3xd73RpCx/view?usp=sharing",
            "imgAlt": "nara-nou",
            "projectUrl": "-",
            "modalId": "nara-nou",
            "bio_en": "In my opinion, information is the power where the data is the main root of information. Hence, in our living we really need data in order to expand our non-blundering knowledge. In my career life, I utmost need the data for aggregating the information of project progress, beneficiaries, agriculture farms, agricultural business, economic trend and how the country economic trend in another 5 or 10 years. Without data, I am nothing and I can’t live or distribute to my society to change to be better. The ODC Literacy Training program is vital for person who works in the field of management and reporting. This program is utmost value for me to shape my professional data management as well as conducting research. I have gained lots of competency on data sourcing, data cleaning; data tool utilizing which comprehensively understand and are helpful. I expect that after the training, I will become one of professional data sourcing, good reporter and data trainers whom are my under-supervised staffs in organization.",
            "bio_km": "សម្រាប់​ខ្ញុំ ព័ត៌មាន​ជា​អំណាច ឯទិន្នន័យ​ជា​ឬសគ​ល់​ចំបង​នៃ​ព័ត៌មាន។ ដូច្នេះ ក្នុង​ការរស់នៅ យើង​ត្រូវការ​ទិន្នន័យ​ដើម្បី​ពង្រីក​ចំណេះដឹង​របស់​យើង។ ក្នុង​កិច្ចការ​ងារ​របស់ខ្ញុំ ខ្ញុំ​ពិតជា​ត្រូវការ​ទិន្នន័យ​ដើម្បី​ទាញ​យក​ព័ត៌មាន​នៃ​គម្រោង អ្នកទទួល​ផល ចំការ​កសិកម្ម មុខរបរ​កសិកម្ម និន្នាការ​សេដ្ឋកិច្ច ក៏ដូចជា​ស្ថានភាព​នៃ​និន្នាការ​សេដ្ឋកិច្ច​របស់​កម្ពុជា​ក្នុងរយៈពេល៥ ទៅ ១០ឆ្នាំខាងមុខ​ទៀត។ បើសិន​គ្មាន​ទិន្នន័យ ខ្ញុំ​នឹង​គ្មានអ្វី​ដើម្បី​ផ្តល់​ទៅកាន់​សង្គមជាតិ​វិញ​នោះ​ទេ។ កម្មវិធី​អក្ខរកម្ម​ទិន្នន័យ​របស់ អូ​ឌី​ស៊ី ពិតជា​មាន​សារៈសំខាន់​ ជាពិសេស​សម្រាប់​អ្នកធ្វើការ​ក្នុង​ការគ្រប់គ្រង និង​ការ​ធ្វើ​របាយការណ៍។ កម្មវិធី​នេះ​ពិតជា​មានតម្លៃ​ណាស់ ព្រោះ​ខ្ញុំ​អាច​ពង្រឹង​ការគ្រប់គ្រង​ទិន្នន័យ ក៏ដូចជា​ការសិក្សា​ស្រាវជ្រាវ​របស់ខ្ញុំ។ ខ្ញុំ​បាន​ទទួល​ចំណេះដឹង និង​សមត្ថភាព​ទាក់ទង​នឹង​ប្រភព​ទិន្នន័យ ការ​សំអាត​ទិន្នន័យ កម្មវិធី​ដើម្បី​បម្លែង​ទិន្នន័យ​ទៅជា​ទម្រង់​ដែល​ងាយស្រួល​យល់ជា​ដើម។ ខ្ញុំ​រំពឹង​ថា ខ្ញុំ​នឹង​ក្លាយជា​អ្នក​ទាញ​យក​ទិន្នន័យ និង​អ្នករាយការណ៍​ដ៏​ល្អ​ម្នាក់។ ខ្ញុំ​ក៏​ចង់​ក្លាយជា​អ្នក​បណ្តុះបណ្តាល​អំពី​ទិន្នន័យ​ទៅកាន់​មិត្ត​រួមការ​ងារ​ផង​ដែរ។",
            "wpImgUrl": "https://opendevelopmentcambodia.net/wp-content/uploads/sites/2/2020/04/nara-nou-min.jpg"
        },
        {
            "surname": "NEN",
            "givenName": "Kimla",
            "middleName": "",
            "is_ready": "yes",
            "name_en": "NEN Kimla",
            "name_km": "និន គឹមឡា",
            "position_en": "Monitoring, Evaluation and Learning Specialist/",
            "position_km": "ប្រឹក្សាត្រួតពិនិត្យ និងវាយតម្លៃគម្រោង",
            "organization_en": "Voluntary Service Oversea (VSO)",
            "organization_km": "អង្គការ​អ្នក​ស្ម័គ្រចិត្ត​បំរើ​ការងារ​នៅ​បរទេស​",
            "imgUrl": "https://drive.google.com/file/d/1B7apOXFEVbcJ7u4LRUO5rt2YNBFLPZfr/view?usp=sharing",
            "imgAlt": "nen-kimla",
            "projectUrl": "-",
            "modalId": "nen-kimla",
            "bio_en": "In order to make a good decision, I have to gather data and analyst it significantly. Data could provide us a point of view or deep insight before decision making or changing. It will also contribute to some strategy, critical thinking for management team to betterment plan. From this intervention, I hope I could learn on how to use and fine data properly way, how to interpret data and publication, familiar with some tools on how to collect data, data visualization, write success story or impacts. I wish to produce a success story of Project Idea: Climate Smart Agriculture.",
            "bio_km": "ដើម្បី​អាច​សម្រេចចិត្ត​បាន​ត្រឹមត្រូវ ខ្ញុំ​ត្រូវ​ប្រមូល​ទិន្នន័យ ហើយធ្វើការ​វិភាគ​វា​ឱ្យ​បាន​ច្បាស់លាស់។ ទិន្នន័យ​អាច​ផ្តល់​ឱ្យ​យើង​នូវ​ទស្សនៈ​ ឬការយល់​ដឹង​ស៊ីជម្រៅ។ វា​ក៏​រួមចំណែក​ផ្តល់​នូវ​យុទ្ធ​សាស្រ្ត ការ​ត្រិះរិះ​ពិចារណា​សម្រាប់​ការគ្រប់គ្រង​ដើម្បី​បង្កើត​គម្រោង​ឱ្យ​កាន់តែ​ប្រសើរ។ ខ្ញុំ​សង្ឃឹមថា វគ្គបណ្តុះបណ្តាលនេះ​អាច​ជួយ​ឱ្យ​ខ្ញុំ​រៀន​ពី​វិធី​ស្វែងរក និង​ប្រើប្រាស់​ទិន្នន័យ​បាន​ត្រឹមត្រូវ វិធី​បកប្រែ​ទិន្នន័យ និង​ចេះ​ប្រើប្រាស់​ឧបករណ៍​ប្រើប្រាស់​ប្រមូល​ទិន្នន័យ បម្លែង​ទិន្នន័យ​ជា​រូបភាព និង​សរសេរ​ពី​ផល​នៃ​គម្រោង។ ខ្ញុំ​ចង់​បង្កើតរឿង​ជោគជ័យ​មួយ​ទាក់ទង​នឹង​គម្រោង \"កសិកម្មឆ្លាតវៃសម្របទៅនឹងអាកាសធាតុ​\"។",
            "wpImgUrl": "https://opendevelopmentcambodia.net/wp-content/uploads/sites/2/2017/11/Icon-User-green.png"
        },
        {
            "surname": "NOU",
            "givenName": "Panhaka",
            "middleName": "",
            "is_ready": "no",
            "name_en": "NOU Panhaka",
            "name_km": "",
            "position_en": "",
            "position_km": "",
            "organization_en": "",
            "organization_km": "",
            "imgUrl": "",
            "imgAlt": "nou-panhaka",
            "projectUrl": "-",
            "modalId": "nou-panhaka",
            "bio_en": "",
            "bio_km": "",
            "wpImgUrl": ""
        },
        {
            "surname": "PEN",
            "givenName": "Dina",
            "middleName": "",
            "is_ready": "no",
            "name_en": "PEN Dina",
            "name_km": "",
            "position_en": "Lecturer",
            "position_km": "",
            "organization_en": "Svay Reing University (SRU)",
            "organization_km": "សាកលវិទ្យាល័យខេត្តស្វាយរៀង",
            "imgUrl": "https://drive.google.com/open?id=1Jf_O_15nuirQqQWQ_bkPvE4p6kN-wzgF",
            "imgAlt": "pen-dina",
            "projectUrl": "-",
            "modalId": "pen-dina",
            "bio_en": "He received his Bachelor’s degree in Education and Master of Education in English) and Master of Social Science and Law in Political Science And had been trained for two years at pedagogy school, Regional Teacher Training Centre in Prey Veng, and one year at National Institute of Education (NIE) in Phnom Penh. Mr. Dina had first taught at Svay Rieng High School for over 5 years since 2002 and started teaching at Svay Rieng University afterward, in his position as a lecturer of English, he has taught various subjects in English; Foundation of Education, Academic Writing Skills and Literature Studies. Each academic year, he is assigned as a supervisor teacher for a teaching practicum of his senior students before they can complete their course. He has compiled and developed course books used as teaching materials. Recently this academic year, he has developed a new course book, English for Public Administration for Non-English Major who are doing their Bachelor in Public Administration. Besides, he had worked as an officer at the Research and Development office for five years and his interest in research is Education. Mr. PEN Dina is a very open-mind, optimistic, creative, good-team work, pleasant personalities and friendly toward other staff and colleagues. In his free time he likes reading, writing and exploring new things, still he likes to learn new thing to upgrade his ability and professional teaching skills as well as research.",
            "bio_km": "",
            "wpImgUrl": ""
        },
        {
            "surname": "PHOUNG",
            "givenName": "Vantha",
            "middleName": "",
            "is_ready": "no",
            "name_en": "PHOUNG Vantha",
            "name_km": "",
            "position_en": "",
            "position_km": "",
            "organization_en": "",
            "organization_km": "",
            "imgUrl": "",
            "imgAlt": "phoung-vantha",
            "projectUrl": "-",
            "modalId": "phoung-vantha",
            "bio_en": "",
            "bio_km": "",
            "wpImgUrl": ""
        },
        {
            "surname": "PHOURN",
            "givenName": "Yu",
            "middleName": "",
            "is_ready": "yes",
            "name_en": "PHOURN Yu",
            "name_km": "ភួន យូ",
            "position_en": "Media and Communication Coordinator",
            "position_km": "អ្នកសម្របសម្រួលសារព័ត៌មាន និងទំនាក់ទំនង",
            "organization_en": "The NGO Forum on Cambodia",
            "organization_km": "វេទិកានៃអង្គការមិនមែនរដ្ឋាភិបាល ស្តីពីកម្ពុជា",
            "imgUrl": "https://drive.google.com/file/d/18mcOmOcYIhunR5fNUejLe2VtEasypfEy/view?usp=sharing",
            "imgAlt": "phourn-yu",
            "projectUrl": "-",
            "modalId": "phourn-yu",
            "bio_en": "Data is important to me because it is the source for purpose for any organization or individual who use it for any purpose, to analyse and to evidence for the data. From this training, I will learn more understanding on data, using data, analyse data and develop data visualize..etc. I want to achieve this training in the ability as Data Journalist and researcher.",
            "bio_km": "ទិន្នន័យមានសារៈសំខាន់សម្រាប់ខ្ញុំ ព្រោះវាជាប្រភពនៃគោលបំណងសម្រាប់អង្គការ ឬបុគ្គលណាដែលប្រើវាសម្រាប់វិភាគ និងជាភស្តុតាងសម្រាប់ព័ត៌មាន។ ក្នុងវគ្គបណ្តុះបណ្តាលនេះ ខ្ញុំនឹងរៀនស្វែងយល់បន្ថែមលើទិន្នន័យ ការប្រើប្រាស់ និងវិភាគទិន្នន័យ។ ខ្ញុំចង់ទទួលបានការបណ្តុះបណ្តាលនេះក្នុងនាមជាអ្នកសារព័ត៌មាននិងអ្នកស្រាវជ្រាវ។ ",
            "wpImgUrl": "https://opendevelopmentcambodia.net/wp-content/uploads/sites/2/2020/04/phourn-yu-min.jpg"
        },
        {
            "surname": "ROEUN",
            "givenName": "Narith",
            "middleName": "",
            "is_ready": "no",
            "name_en": "ROEUN Narith",
            "name_km": "",
            "position_en": "Research Associate",
            "position_km": "មន្រ្តីទំនាក់ទំនង",
            "organization_en": "Cambodia Development Resource Institute",
            "organization_km": "វិទ្យាស្ថានបណ្តុះបណ្តាល និងស្រាវជ្រាវដើម្បីអភិវឌ្ឍន៍កម្ពុជា",
            "imgUrl": "https://drive.google.com/file/d/1FMGsX-MgAqB63rNPjwwjRYMT2Z_uXQHV/view?usp=sharing",
            "imgAlt": "roeun-narith",
            "projectUrl": "-",
            "modalId": "roeun-narith",
            "bio_en": "Agricultural trade between China and Mekong-Lancang countries: A value chain analysis. His expertise is on value chain analysis (VCA) and policy analysis matrix (PAM). With education background and work experience, his future interest is related to competitiveness analysis in association with industries, trade and value chain-related topics. Data literacy is extremely beneficial for him as a researcher and an author of several coming articles. Knowledge to improve the quality of data management, data analysis as well as data visualization is expected to acquire from the course.",
            "bio_km": "",
            "wpImgUrl": "https://opendevelopmentcambodia.net/wp-content/uploads/sites/2/2020/04/roeun-narith-min.jpg"
        },
        {
            "surname": "SAN",
            "givenName": "Sothear",
            "middleName": "",
            "is_ready": "yes",
            "name_en": "SAN Sothear",
            "name_km": "សាន្ត​ ​សុធា",
            "position_en": "Independent Researcher",
            "position_km": "អ្នកសិក្សាស្រាវជ្រាវឯករាជ្យ",
            "organization_en": "Khon Kaen University",
            "organization_km": "សាកវិទ្យាល័យខនកេន​​",
            "imgUrl": "https://drive.google.com/file/d/1anTPrW4zK3EvuRH08SWe0nJYWHeTK6LX/view?usp=sharing",
            "imgAlt": "san-sothear",
            "projectUrl": "-",
            "modalId": "san-sothear",
            "bio_en": "Data literacy — the ability to read, write and communicate data in context — is among the most important abilities for organizations today. So, it's supply and demand. The demand is technology, and the supply needs to be data literate. In the training, I expect to further my knowledge on advanced data search, data utilization, and creative data interpretation and presentation. After the training, I want to produce a project on the Trend of Micro-nutrients deficiencies in Cambodia story.This trend story will raise people's awareness of the situation of micronutrient deficiencies in Cambodia, and will be highlighting the areas (targeted provinces) that the government can focus nutritional program on more.",
            "bio_km": "អក្ខរកម្មទិន្នន័យ ដែលជាសមត្ថភាពក្នុងការអាន សរសេរ និងបកប្រែទិន្នន័យ គឺជាសមត្ថភាពមួយដ៏សំខាន់នាពេលបច្ចុប្បន្ន។ វាដូចជាការផ្គត់ផ្គង់ និងតម្រូវការ ដែលតម្រូវការគឺបច្ចេកវិទ្យា ហើយការផ្គត់ផ្គង់ជាអក្ខរកម្មទិន្នន័យ។ ខ្ញុំសង្ឃឹមថា​ ខ្ញុំនឹងបានពង្រឹងចំណេះដឹងក្នុងការស្វែងរកទិន្នន័យ ការប្រើប្រាស់ទិន្នន័យ ក៏ដូចការបកប្រែ និងបង្ហាយទិន្នន័យប្រកបដោយភាពច្នៃប្រឌិត។ បន្ទាប់ពីវគ្គបណ្តុះបណ្តាលនេះ ខ្ញុំចង់ធ្វើគម្រោងមួយស្តីពី និន្នាការកង្វះមីក្រូសារជាតិ​នៅកម្ពុជា។ គម្រោងនេះនឹងអាចជួយលើកកម្ពស់ការយល់ដឹងរបស់ប្រជាជនកម្ពុជា ទៅលើស្ថានភាពនៃកង្វះមីក្រូសារជាតិ​នៅកម្ពុជា ហើយវាក៏នឹងរំលេចផ្នែកសំខាន់ដែលរដ្ឋាបាលអាចគាំទ្របាន។",
            "wpImgUrl": "https://opendevelopmentcambodia.net/wp-content/uploads/sites/2/2017/11/Icon-User-green.png"
        },
        {
            "surname": "Saowalak",
            "givenName": "Jingjungvisut",
            "middleName": "",
            "is_ready": "no",
            "name_en": "Saowalak Jingjungvisut",
            "name_km": "",
            "position_en": "",
            "position_km": "",
            "organization_en": "",
            "organization_km": "",
            "imgUrl": "",
            "imgAlt": "saowalak-jingjungvisut",
            "projectUrl": "-",
            "modalId": "saowalak-jingjungvisut",
            "bio_en": "",
            "bio_km": "",
            "wpImgUrl": ""
        },
        {
            "surname": "SES",
            "givenName": "Vansak",
            "middleName": "",
            "is_ready": "no",
            "name_en": "SES Vansak",
            "name_km": "",
            "position_en": "",
            "position_km": "",
            "organization_en": "",
            "organization_km": "",
            "imgUrl": "",
            "imgAlt": "ses-vansak",
            "projectUrl": "-",
            "modalId": "ses-vansak",
            "bio_en": "",
            "bio_km": "",
            "wpImgUrl": ""
        },
        {
            "surname": "SREY",
            "givenName": "Sopheak",
            "middleName": "",
            "is_ready": "yes",
            "name_en": "SREY Sopheak",
            "name_km": "ស្រី សុភ័ក្រ្ត",
            "position_en": "Online Manager",
            "position_km": "អ្នកគ្រប់គ្រងផ្នែកអនឡាញ",
            "organization_en": "Cambodian Center for Independent Media (CCIM)",
            "organization_km": "មជ្ឈមណ្ឌលកម្ពុជាដើម្បីប្រព័ន្ធផ្សព្វផ្សាយឯករាជ្យ",
            "imgUrl": "https://drive.google.com/open?id=14lU7ed09sxUyKEGNYEooPj2tFRlTZxZi",
            "imgAlt": "srey-sopheak",
            "projectUrl": "-",
            "modalId": "srey-sopheak",
            "bio_en": "Normally, the data could tell a full story in digit and text. It is a solid evidence with complicated code to be read out. It would be better if I could learn and know how to read and interpret data in basic and easy way. After the training, I will be able to research data by using the introduced digital tools, read data in a smart way and interpret the complicated data into the simple way for public audience understandable. I want to be able to create a friendly dynamic infographic and online map for showcasing the safety Cambodian journalist project.",
            "bio_km": "ជាធម្មតា ទិន្នន័យអាចប្រាប់រឿងពេញលេញជាលេខ និងអត្ថបទ។ វាគឺជាភ័ស្តុតាងរឹងមាំដែលមានលេខកូដស្មុគស្មាញដែលត្រូវអាន។ វាជាការប្រសើរ ប្រសិនបើខ្ញុំអាចរៀន និងដឹងពីរបៀបអាន និងបកស្រាយទិន្នន័យតាមវិធីងាយ និងមូលដ្ឋាន។ បន្ទាប់ពីការបណ្តុះបណ្តាល ខ្ញុំនឹងអាចស្រាវជ្រាវទិន្នន័យដោយប្រើកម្មវិធីឌីជីថល អានទិន្នន័យតាមរបៀបឆ្លាតវៃ និងបកស្រាយទិន្នន័យស្មុគស្មាញទៅជាសាមញ្ញសម្រាប់ទស្សនិកជនអាចយល់បាន។ ខ្ញុំចង់បង្កើតផែនទីសម្រាប់បង្ហាញគម្រោងសុវត្ថិភាពអ្នកសារព័ត៌មានកម្ពុជា។",
            "wpImgUrl": "https://opendevelopmentcambodia.net/wp-content/uploads/sites/2/2020/04/srey-sopheak-min.jpg"
        },
        {
            "surname": "VEN",
            "givenName": "Saroeut",
            "middleName": "",
            "is_ready": "no",
            "name_en": "VEN Saroeut",
            "name_km": "",
            "position_en": "",
            "position_km": "",
            "organization_en": "",
            "organization_km": "",
            "imgUrl": "",
            "imgAlt": "ven-saroeut",
            "projectUrl": "-",
            "modalId": "ven-saroeut",
            "bio_en": "",
            "bio_km": "",
            "wpImgUrl": ""
        },
        {
            "surname": "YENG",
            "givenName": "Sopheng",
            "middleName": "",
            "is_ready": "yes",
            "name_en": "YENG Sopheng",
            "name_km": "យេង សុផេង",
            "position_en": "Internship Coordinator",
            "position_km": "បុគលិកសម្របសម្រួលកម្នសិក្សាសិស្ស",
            "organization_en": "Pour un Sourire d'Enfant (PSE)",
            "organization_km": "សមាគមយុវជនខ្មែរ",
            "imgUrl": "https://drive.google.com/file/d/1V2Lgq6QYTeZKbVkdWvU_yHSPYP9FHAuH/view?usp=sharing",
            "imgAlt": "yeng-sopheng",
            "projectUrl": "-",
            "modalId": "yeng-sopheng",
            "bio_en": "Data is very important and necessary for my working as researcher and project development. I worked with data like collecting, analyse, writing result from data and presentation data analysing to manager and donor. Especially, data help me to make right decision. I expect from the training such as first, I can learn more technique to get data or source from internet. Second, I can use new tool to collect data and analyse program for data. Last one, I had experience to write data story relate to vocational training. I plan to release one story about the role of vocational training with development in Cambodia. This story will tell audience about important role and challenge of TVET program.",
            "bio_km": "ទិន្នន័យមានសារៈសំខាន់ និងចាំបាច់ណាស់សម្រាប់ការងាររបស់ខ្ញុំក្នុងនាមជាអ្នកស្រាវជ្រាវ និងអភិវឌ្ឍគម្រោង។ ខ្ញុំបានធ្វើការជាមួយទិន្នន័យដូចជា ការប្រមូល ការវិភាគ ការសរសេរលទ្ធផលពីទិន្នន័យ និងការធ្វើបទបង្ហាញដល់អ្នកគ្រប់គ្រង និងម្ចាស់ជំនួយ។ ជាពិសេស ទិន្នន័យជួយខ្ញុំឱ្យធ្វើការសម្រេចចិត្តត្រឹមត្រូវ។ ការបណ្តុះបណ្តាលនេះ ខ្ញុំរំពឹងថា ខ្ញុំអាចរៀនបច្ចេកទេសបន្ថែមទៀត ដើម្បីទទួលបានទិន្នន័យ ឬប្រភពទិន្នន័យពីអ៊ីនធឺណិត។ ទីពីរ ខ្ញុំអាចប្រើឧបករណ៍ថ្មីៗ ដើម្បីប្រមូលទិន្នន័យ និងវិភាគកម្មវិធីសម្រាប់ទិន្នន័យ។ ចុងក្រោយខ្ញុំចង់មានបទពិសោធន៍ក្នុងការសរសេររឿងរ៉ាវទិន្នន័យទាក់ទងនឹងការបណ្តុះបណ្តាលវិជ្ជាជីវៈ។ ខ្ញុំគ្រោងនឹងចេញផ្សាយរឿងមួយស្តីពី តួនាទីនៃការបណ្តុះបណ្តាលវិជ្ជាជីវៈ និងការអភិវឌ្ឍនៅក្នុងប្រទេសកម្ពុជា។",
            "wpImgUrl": "https://opendevelopmentcambodia.net/wp-content/uploads/sites/2/2020/04/yeng-sopheng-min.jpg"
        }
    ]
);